### ISSUE TITLE
I am able to succesfully run this in cmd window  but how can i get the full http call

### ISSUE THREAD

**Issue by Abhi001vj** [explosion/spacy-services#6]
I tried building the http call using requests library but it gives me a status error 500.
```
import requests

d = {"text":"I am Abhi and I am from India.", "model":"en"}
r  = requests.post("http://localhost:8000/dep", params=d)

# then i tried passing it the data as json
url = 'http://localhost:8000/dep'

headers = {'content-type': 'application/json'}
response = requests.post(url, data=json.dumps(d), headers=headers)

# to get the json output
r.text 
print(r.url)  # to get the http url 
```
 I am sorry if this is such a silly doubt but i cant figure it out ,I need to build the http request to make these calls from a program right and i hope you can help me.
Thank you.

**Comment by ines** [comment]
What happens if you set the content type header to `text/plain` instead of `application/json`?

Aside from that, your request looks fine – for reference, [here's how it looks in JavaScript for displaCy](https://github.com/explosion/displacy/blob/master/assets/js/displacy.js#L33), which uses the same REST service.

**Comment by Abhi001vj** [comment]
It worked .I dont know what happened it now works.
`url = "http://localhost:8000/dep"

 headers = {'content-type': 'application/json'}
 d = {"text": message_text, "model":"en"}
 response = requests.post(url, data=json.dumps(d), headers=headers)
 r = response.json()`

**Comment by Abhi001vj** [comment]
Thank you for the reply.
